### ISSUE TITLE
Doc tests failing due to broken links in upstream protos

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-dataproc#514]
We should fix or remove the links causing doc tests to fail, because this is blocking us from updating the library without using admin.

Refs: https://github.com/googleapis/nodejs-dataproc/pull/512

**Comment by meredithslota** [comment]
@bcoe It looks like #512 is closed — what needs to be done here?

**Comment by bcoe** [comment]
@meredithslota I updated to latest version of library, which removes the `v1beta2` API, things seem to be fine now with links 👍
